export const BOOKS = {
  foundation: {
    title: '基地',
    english: 'Foundation',
    group: '基地',
    order: 1,
    role: '审判、四王国、科学教与贸易危机',
    url: 'https://www.penguinrandomhouse.com/books/5655/foundation-by-isaac-asimov/paperback/',
  },
  empire: {
    title: '基地与帝国',
    english: 'Foundation and Empire',
    group: '基地',
    order: 2,
    role: '帝国反攻与骡造成的计划失效',
    url: 'https://www.penguinrandomhouseretail.com/book/?isbn=9780553382587',
  },
  second: {
    title: '第二基地',
    english: 'Second Foundation',
    group: '基地',
    order: 3,
    role: '隐秘干预、搜寻与独立思考的代价',
    url: 'https://www.randomhousebooks.com/books/5756/',
  },
  edge: {
    title: '基地边缘',
    english: 'Foundation’s Edge',
    group: '基地',
    order: 4,
    role: '后续阅读：两座基地之外的文明道路',
    url: 'https://www.penguinrandomhouse.com/series/FOU/foundation/',
  },
  earth: {
    title: '基地与地球',
    english: 'Foundation and Earth',
    group: '基地',
    order: 5,
    role: '后续阅读：人类起源与未来道路',
    url: 'https://www.penguinrandomhouse.com/series/FOU/foundation/',
  },
  prelude: {
    title: '基地前奏',
    english: 'Prelude to Foundation',
    group: '基地',
    order: 6,
    role: '前传：心理史学如何成为计划',
    url: 'https://www.penguinrandomhouse.com/series/FOU/foundation/',
  },
  forward: {
    title: '迈向基地',
    english: 'Forward the Foundation',
    group: '基地',
    order: 7,
    role: '前传：谢顿的事业与继承者',
    url: 'https://www.penguinrandomhouse.com/series/FOU/foundation/',
  },
  stars: {
    title: '繁星若尘',
    english: 'The Stars, Like Dust',
    group: '帝国',
    order: 8,
    role: '世界背景阅读',
    url: 'https://books.google.com/books/about/Triangle.html?id=iNc2AAAAIAAJ',
  },
  currents: {
    title: '星空暗流',
    english: 'The Currents of Space',
    group: '帝国',
    order: 9,
    role: '世界背景阅读',
    url: 'https://books.google.com/books/about/Triangle.html?id=iNc2AAAAIAAJ',
  },
  pebble: {
    title: '苍穹微石',
    english: 'Pebble in the Sky',
    group: '帝国',
    order: 10,
    role: '世界背景阅读',
    url: 'https://books.google.com/books/about/Triangle.html?id=iNc2AAAAIAAJ',
  },
  robot: {
    title: '我，机器人',
    english: 'I, Robot',
    group: '机器人',
    order: 11,
    role: '机器人短篇集；常见中文合集中收入此卷',
    url: 'https://www.penguinrandomhouseretail.com/book/?isbn=9798217093472',
  },
  steel: {
    title: '钢穴',
    english: 'The Caves of Steel',
    group: '机器人',
    order: 12,
    role: '机器人长篇阅读',
    url: 'https://www.penguinrandomhouseretail.com/book/?isbn=9798217093472',
  },
  naked: {
    title: '裸阳',
    english: 'The Naked Sun',
    group: '机器人',
    order: 13,
    role: '机器人长篇阅读',
    url: 'https://www.penguinrandomhouseretail.com/book/?isbn=9798217093472',
  },
  dawn: {
    title: '曙光中的机器人',
    english: 'The Robots of Dawn',
    group: '机器人',
    order: 14,
    role: '机器人长篇阅读',
    url: 'https://www.penguinrandomhouseretail.com/book/?isbn=9798217093472',
  },
  robotsEmpire: {
    title: '机器人与帝国',
    english: 'Robots and Empire',
    group: '机器人',
    order: 15,
    role: '连接机器人时代与帝国背景的阅读',
    url: 'https://penguinrandomhouselibrary.com/author/?authorid=947',
  },
} as const;
export type BookId = keyof typeof BOOKS;
export const STORY_SOURCES = {
  foundation: 'https://en.wikipedia.org/wiki/Foundation_(Asimov_novel)',
  empire: 'https://en.wikipedia.org/wiki/Foundation_and_Empire',
  second: 'https://en.wikipedia.org/wiki/Second_Foundation',
} as const;
